<?php

/**
 * Class DB
 */
class DB
{
	protected static $_instance;

	/**
	 * @var false|mysqli
	 */
	private $connect;

	/**
	 * DB constructor.
	 */
	private function __construct()
	{
		//bd connection
		$this->connect = mysqli_connect(HOST, DB_USER, DB_PASSWORD,
			DATABASE) or die("No connection to DB! " . mysqli_connect_error());

		mysqli_select_db($this->connect, DATABASE) or die ("Can't select DB " . mysqli_error());
	}

	/**
	 * @return DB
	 */
	public static function getInstance()
	{
		if (self::$_instance === null) {
			self::$_instance = new self;
		}
		return self::$_instance;
	}

	/**
	 * @param $sql
	 * @return bool|mysqli_result
	 */
	public static function query($sql)
	{
		$obj = self::$_instance;
		if (isset($obj->connect)) {
			$start_time_sql = microtime(true);
			mysqli_query($obj->connect,
				"SET NAMES utf8") or die(mysqli_error($obj->connect));

			$result = mysqli_query($obj->connect,
				$sql) or die(mysqli_error($obj->connect));

			$time_sql = microtime(true) - $start_time_sql;

			if (DEBUG == true) {
				echo "<br/><br/><span style='color:white'> <span style='color:green'># N " . $obj->count_sql . ": </span>" . $sql . "</span> <span style='color:green'>(" . round($time_sql,
						5) . " msec )</span>";
			}
			return $result;
		}
		return false;
	}

	/**
	 * @param $object
	 * @return bool
	 */
	public static function fetch_object($object)
	{
		return mysqli_fetch_object($object,
				MYSQLI_ASSOC) or die("<br/><span style='color:red'>SQL fetch ERROR:</span> " . mysqli_error($object));
	}

	/**
	 * @param $object
	 * @return bool|int
	 */
	public static function num_rows($object)
	{
		if ($object->num_rows > 0) {
			return mysqli_num_rows($object) or die("<br/><span style='color:red'>SQL num ERROR:</span> " . mysqli_error($object->connect));
		} else {
			return 0;
		}
	}

	/**
	 * returns the entry as an array
	 *
	 * @param $object
	 * @return array|null
	 */
	public static function fetch_array($object)
	{
		return mysqli_fetch_array($object);
	}

	/**
	 * mysql_insert_id() returns the ID generated by the AUTO_INCREMENT column of the last INSERT request to the server
	 *
	 * @return int|string
	 */
	public static function insert_id()
	{
		$obj = self::$_instance;
		return mysqli_insert_id($obj->connect);
	}

	/**
	 * esc symbols
	 * @param $what
	 * @return string
	 */
	public static function esc($what)
	{
		$obj = self::$_instance;
		return mysqli_real_escape_string($obj->connect, trim($what));
	}

}